workflows:
  android-workflow:
    name: Build APK
    max_build_duration: 60
    environment:
      vars:
        ANDROID_KEYSTORE_PASSWORD: Encrypted
    scripts:
      - name: Build debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
